services:
- type: web
  name: bookapp
  runtime: ruby
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: bundle install && bundle exec rails db:migrate && RAILS_ENV=produciton bundle exec rails assets:precompile
  startCommand: bundle exec rails server

databases:
  - name: appdb
    user: appdb
    databaseName: noteappdb
    plan: free

version: "1"
